### ISSUE TITLE
Settings GUI

### ISSUE THREAD

**Issue by gabelluardo** [policumbent/marta-ui#17]
- [ ] Aggiungere scelta intervallo pacchetti
- [ ] Aggiungere switch card grafici (#10)
- [ ] Gestire il footer (#2)
- [ ] Disattivare opzioni di debug (#16)
